### ISSUE TITLE
Libxml not loading Phoenix

### ISSUE THREAD

**Issue by umitcel** [melpon/libxml#1]
Hi I try to integrate libxml into a phoenix application it is not loaded.

**Comment by melpon** [comment]
Libxml is working in my environment with phoenix (Mac, libxml-1.0.4, phoenix-1.3.0).
Please tell me your environment.

**Comment by umitcel** [comment]
it has worked in a clean ubuntu install. thanks. But I think not all functions implemented. for example do you think to implement xmlSchemaNewParserCtxt function?

**Comment by melpon** [comment]
Yes. Since the libxml2 library has so many functions, I only implement the necessary functions to me.
What functions are you need? I will implement these functions preferentially.

**Comment by umitcel** [comment]
I need xsd validation capability functions of libxml. From a C example program below functions are used.

xmlSchemaNewParserCtxt
xmlSchemaParse
xmlSchemaNewValidCtxt
xmlSchemaValidateDoc
xmlSchemaFreeParserCtxt
xmlSchemaFree
xmlSchemaFreeValidCtxt
xmlSetStructuredErrorFunc
xmlSetGenericErrorFunc
xmlThrDefSetStructuredErrorFunc
xmlThrDefSetGenericErrorFunc

**Comment by melpon** [comment]
I just released libxml-1.1.0. It contains XML Schema functions. Please refer to above commit tests for usage.

**Comment by umitcel** [comment]
Hi Melpon, great. have you implemented any callback err function to show error details?

xmlSetStructuredErrorFunc(NULL, NULL);
    xmlSetGenericErrorFunc(NULL, handleValidationError);
    xmlThrDefSetStructuredErrorFunc(NULL, NULL);
    xmlThrDefSetGenericErrorFunc(NULL, handleValidationError);

Please check the stackoverflow link for the example;
https://stackoverflow.com/questions/6284827/why-does-this-xml-validation-via-xsd-fail-in-libxml2-but-succeed-in-xmllint-an

**Comment by melpon** [comment]
Do you need these callback functions? It does not seem to need for verification.

**Comment by umitcel** [comment]
But otherwise How can i the error details to user

**Comment by melpon** [comment]
By default, the error details are printed on stderr. If validation is failed, `Libxml.Nif.xml_schema_validate_doc/2` returns non-zero value.

**Comment by umitcel** [comment]
Do you suggest reading error output in a web based app, it would be good if i could store error details in a string

**Comment by melpon** [comment]
I just released libxml-1.1.1. `Libxml.Nif.xml_schema_validate_doc/2` and `Libxml.Schema.validate_doc/2` returns error details (see [test code](https://github.com/melpon/libxml/blob/be7f1852b3a48e3756a27d848c6f24532762bac3/test/libxml_test.exs#L359-L371)).

**Comment by umitcel** [comment]
Hi melpon, with version 1.1.2 I get below error
 
![image](https://user-images.githubusercontent.com/5739535/35510561-9a4683bc-0509-11e8-8425-7b6225577140.png)

**Comment by melpon** [comment]
`Libxml.Nif.xml_schema_parse/1` now returns error details in 1.1.2. Use `{:ok, {schema, errors}} = ...`  instead of `{:ok, schema} = ...`.

**Comment by melpon** [comment]
Did you solve? If so I will close the issue.

**Comment by umitcel** [comment]
Sorry for feedback, yes it is solved. 
By the way how can I donate?

**Comment by melpon** [comment]
I don't need a donation. But thanks anyway.
